apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: go-proxy
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-proxy
    spec:
      containers:
      - name: go-proxy
        image: alexellis2/go-proxy-experiment:2018-06-10
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
