---
apiVersion: v1
kind: Service
metadata:
  name: go-proxy
  namespace: openfaas
  labels:
    app: go-proxy
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31115
  selector:
    app: go-proxy
